### ISSUE TITLE
Error when creating an issue with a too long description

### ISSUE THREAD

**Issue by qlereboursBS** [BearStudio/start-repo#29]
## Issue
I tried to create an issue with a 3 lines description, and it failed:

![image](https://user-images.githubusercontent.com/27200095/161243738-ca6beb5b-4ac6-4261-83c1-eb2aeac24485.png)

## Test data
I tested with the following description:
> Most of the time, the users have different roles (user, admin...). To have a good start, it's better to set them up, and to ensure they are retrieved and usable in the frontend. 
To do so, just implement a simple change in the navbar for instance, depending on the role

**Comment by yoannfleurydev** [comment]
This was a production only issue, this is now fixed. The schema on the `main` branch was out of sync with the code and was not using `text` but `varchar(192)`.
