### ISSUE TITLE
Move some logic to the backend

### ISSUE THREAD

**Issue by yoannfleurydev** [BearStudio/start-repo#38]
This can probably be set in the backend to avoid client side computation and enjoy tRPC typings.

_Originally posted by @yoannfleurydev in https://github.com/BearStudio/start-repo/pull/37#discussion_r928064346_

**Comment by garimellasrisudha** [comment]
Hi ,
Can you elaborate what exactly we have to do?
Apricate the efforts 
Thank you

**Comment by yoannfleurydev** [comment]
> Hi , Can you elaborate what exactly we have to do? Apricate the efforts Thank you

Hi,

Those lines https://github.com/BearStudio/start-repo/blob/7867ec2133b52644d08f9cb173ab23c7d8e8d055/src/app/accounts/PageAccounts.tsx#L24-L25 are, at the moment computed on the frontend (client side). This is a note to remind me that this logic can be put in the backend, as this project is using tRPC, the data retrieval will be typed with `github` and `gitlab` keys.

https://github.com/BearStudio/start-repo/pull/37#discussion_r928064346
